# Generated by Django 5.1.1 on 2024-09-19 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ITNDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_id', models.CharField(max_length=50, unique=True)),
                ('household_head_name', models.CharField(max_length=100)),
                ('number_of_family_members', models.PositiveIntegerField()),
                ('itns_distributed', models.PositiveIntegerField()),
                ('distribution_date', models.DateField()),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
