# Generated by Django 5.1.1 on 2024-09-21 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ITN', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itndistribution',
            old_name='distributor',
            new_name='distributor_id',
        ),
    ]
