# Generated by Django 5.1.1 on 2024-09-21 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ITN', '0002_rename_distributor_itndistribution_distributor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itndistribution',
            old_name='distributor_id',
            new_name='distributor',
        ),
    ]
