# Generated by Django 5.1.1 on 2024-09-21 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ITN', '0003_rename_distributor_id_itndistribution_distributor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itndistribution',
            old_name='distributor',
            new_name='distributor_id',
        ),
    ]
