# Generated by Django 5.1.1 on 2024-09-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITN', '0004_rename_distributor_itndistribution_distributor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itndistribution',
            name='distributor_id',
            field=models.IntegerField(),
        ),
    ]
